name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    environment:
        name: DEV
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: echo a string
        run: echo "Hello world test 1 -- ${{secrets.MY_NEW_SECRET}} TT -- ${{secrets.MY_SECRET}}"
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
